version: '3.8'

services:
  client:
    build:
      context: ../client
      dockerfile: Dockerfile  # Specify the correct name
    ports:
      - "3000:3000"

  server:
    build:
      context: ../server
      dockerfile: Dockerfile  # Specify the correct name
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/numer
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
